# Generated by Django 5.1.1 on 2024-10-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_owner'),
        # ('favorites', '0002_favoritem2m_delete_favorite'),
        ('shop', '0004_alter_nftproduct_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='users_added', through='favorites.FavoriteM2M', to='shop.nftproduct'),
        ),
    ]
