# Generated by Django 5.1.1 on 2024-10-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_favorite_profile_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='nft',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='profile',
        ),
    ]
