# Generated by Django 5.1.1 on 2024-09-16 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='shop_catego_slug_5ac49f_idx')],
            },
        ),
        migrations.CreateModel(
            name='NftProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nft', models.ImageField(upload_to='shop/%Y/%m/%d')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['name'], name='shop_nftpro_name_225915_idx'), models.Index(fields=['is_sale'], name='shop_nftpro_is_sale_c2d5da_idx')],
            },
        ),
    ]
