# Generated by Django 5.1.1 on 2024-09-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_nftproduct_description_nftproduct_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nftproduct',
            old_name='categories',
            new_name='category',
        ),
    ]
